--!jinja
-- Create the Notebooks
--USE SCHEMA {{env}}_SCHEMA;

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_EU"')
    FROM '@"USD_SPOT_EXCHANGE"."INTEGRATIONS"."USDSE_GIT_REPO"/branches/"{{branch}}"/notebooks/US_EU/'
    QUERY_WAREHOUSE = 'USDSE_WH'
    MAIN_FILE = 'US_EU.ipynb';

ALTER NOTEBOOK "USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_EU" ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_UK"')
    FROM '@"USD_SPOT_EXCHANGE"."INTEGRATIONS"."USDSE_GIT_REPO"/branches/"{{branch}}"/notebooks/US_UK/'
    QUERY_WAREHOUSE = 'USDSE_WH'
    MAIN_FILE = 'US_UK.ipynb';

ALTER NOTEBOOK "USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_UK" ADD LIVE VERSION FROM LAST;