--!jinja
-- Create the Notebooks
--USE SCHEMA {{env}}_SCHEMA;

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_EU"')
    FROM '@"USD_SPOT_EXCHANGE"."INTEGRATIONS"."USDSE_GIT_REPO"/branches/"{{branch}}"/notebooks/US_EU/'
    QUERY_WAREHOUSE = 'USDSE_WH'
    MAIN_FILE = 'US_EU.ipynb';

ALTER NOTEBOOK "USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_US_EU" ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK IDENTIFIER('"USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_SETUP_PIPELINE"')
    FROM '@"USD_SPOT_EXCHANGE"."INTEGRATIONS"."USDSE_GIT_REPO"/branches/"{{branch}}"/notebooks/{{env}}_SETUP_PIPELINE/'
    QUERY_WAREHOUSE = 'USDSE_WH'
    MAIN_FILE = 'SETUP_PIPELINE.ipynb';

ALTER NOTEBOOK "USD_SPOT_EXCHANGE"."{{env}}_SCHEMA"."{{env}}_SETUP_PIPELINE" ADD LIVE VERSION FROM LAST;